version: '0.1'

volumes:
  db:
    driver: local
  redis:
    driver: local
  mqtt:
    driver: local

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - dashboard
    expose:
      - 80
  postgres:
    env_file:
      - .env
    image: "postgres:alpine"
    # command: postgres -c config_file=/etc/postgresql.conf
    environment:
      # PGUSER: ${POSTGRES_USER}
      POSTGRES_DB: db
      # POSTGRES_PASSWORD: 123456
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./customPostgresql.conf:/etc/postgresql.conf
    ports:
      - 5432:5432
    expose:
      - 5432
  redis:
    image: "redis:alpine"
    volumes:
      - redis:/data
  mqtt:
    volumes:
      - mqtt:/mosquitto/data
      - mqtt:/mosquitto/log
    build: 
      context: ./
      dockerfile: ./mqtt-Dockerfile
    ports:
      - 8883:8883
      - 1883:1883
  dashboard :
    env_file:
      - .env
    build: 
      context: ./
      dockerfile: ./dashboard/Dockerfile
    restart: always
    ports:
      - 3000:3000
    links: 
      - "postgres:db"

    # expose:
    #   - 3000
  api:
    env_file:
      - .env
    build: 
      context: ./
      dockerfile: ./API/Dockerfile
    restart: always
    depends_on:
      - redis
      - postgres
      - mqtt
    links: 
      - "mqtt:broker"
      - "redis:redis"
      - "postgres:db"
    expose:
      - 8080
  frontend:
    build: 
      context: ./
      dockerfile: ./frontend/Dockerfile
    restart: always
    depends_on:
      - api
      - postgres
    ports:
      - 3005:3000