version: '0.1'

volumes:
  db:
    driver: local
  redis:
    driver: local
  mqtt:
    driver: local

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
  postgres:
    env_file:
      - .env
    image: "postgres:alpine"
    # command: postgres -c config_file=/etc/postgresql.conf
    environment:
      - POSTGRES_DB=db
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./customPostgresql.conf:/etc/postgresql.conf
  redis:
    image: "redis:alpine"
    volumes:
      - redis:/data
  mqtt:
    volumes:
      - mqtt:/mosquitto/data
      - mqtt:/mosquitto/log
    build: 
      context: ./
      dockerfile: ./mqtt-Dockerfile
    ports:
      - 8883:8883
  api:
    env_file:
      - .env
    build: 
      context: ./
      dockerfile: ./API/Dockerfile
    restart: always
    depends_on:
      - redis
      - postgres
      - mqtt
    links: 
      - "mqtt:broker"
      - "redis:redis"
      - "postgres:db"
    ports:
      - 3000